slam_toolbox:
  ros__parameters:
    # Impostazioni di base
    use_sim_time: true
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /vessel_v2/lidar_2d
    mode: mapping

    # Parametri del sensore e della mappa
    map_resolution: 0.200
    minimum_laser_range: 0.5  # <--- AGGIUNGI QUESTO PER IL WARNING!
    max_laser_range: 50.0 # Usa un valore sensato per il tuo Lidar
    minimum_time_interval: 1.0
    throttle_scans: 2         # Elabora solo 1 scansione su 2, ignorando i cloni.
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000

    # Parametri di ottimizzazione del grafo
    do_loop_closing: true
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45